// Code generated by goplus from math.gp. DO NOT EDIT.
//goplus:v v0.28.0

// Package lo — arithmetic aggregation and range helpers.
//
// These are exact-compatibility reimplementations of samber/lo's math.go
// surface (v1.53.0), authored in Go+ and generated into portable Go. Behavior,
// including integer-division truncation, order-preserving Mode, direction-aware
// ranges, and non-nil empty results, matches upstream so differential and
// property tests hold.
package lo

// Float constrains the floating-point kinds.
type Float interface {
	~float32 | ~float64
}

// Complex constrains the complex kinds.
type Complex interface {
	~complex64 | ~complex128
}

// Ordered constrains kinds that support the ordering operators, matching
// golang.org/x/exp/constraints.Ordered.
type Ordered interface {
	Integer | Float | ~string
}

// Sum adds every element, starting from the zero value.
func Sum[T Float | Integer | Complex](collection []T) T {
	var sum T
	for i := range collection {
		sum += collection[i]
	}
	return sum
}

// SumBy adds the projection of every element.
func SumBy[T any, R Float | Integer | Complex](collection []T, iteratee func(item T) R) R {
	var sum R
	for i := range collection {
		sum += iteratee(collection[i])
	}
	return sum
}

// Product multiplies every element, starting from one.
func Product[T Float | Integer | Complex](collection []T) T {
	var product T = 1
	for i := range collection {
		product *= collection[i]
	}
	return product
}

// ProductBy multiplies the projection of every element.
func ProductBy[T any, R Float | Integer | Complex](collection []T, iteratee func(item T) R) R {
	var product R = 1
	for i := range collection {
		product *= iteratee(collection[i])
	}
	return product
}

// Mean is the arithmetic mean; integer element types truncate. An empty
// collection yields the zero value, matching upstream.
func Mean[T Float | Integer](collection []T) T {
	length := T(len(collection))
	if length == 0 {
		return 0
	}
	return Sum(collection) / length
}

// MeanBy is Mean over a projection.
func MeanBy[T any, R Float | Integer](collection []T, iteratee func(item T) R) R {
	length := R(len(collection))
	if length == 0 {
		return 0
	}
	return SumBy(collection, iteratee) / length
}

// Mode returns every value tied for the highest frequency, in first-reaching
// order. An empty collection yields a non-nil empty slice.
func Mode[T Integer | Float](collection []T) []T {
	if len(collection) == 0 {
		return []T{}
	}
	mode := make([]T, 0)
	maxFreq := 0
	frequency := make(map[T]int)
	for _, item := range collection {
		frequency[item]++
		count := frequency[item]
		if count > maxFreq {
			maxFreq = count
			mode = []T{item}
		} else if count == maxFreq {
			mode = append(mode, item)
		}
	}
	return mode
}

// Clamp constrains value to the inclusive [low, high] interval.
func Clamp[T Ordered](value, low, high T) T {
	if value < low {
		return low
	} else if value > high {
		return high
	}
	return value
}

// Range builds a slice of elementNum integers starting at zero, counting down
// when elementNum is negative.
func Range(elementNum int) []int {
	step := 1
	if elementNum < 0 {
		step = -1
	}
	length := elementNum * step
	result := make([]int, length)
	for i, j := 0, 0; i < length; i, j = i+1, j+step {
		result[i] = j
	}
	return result
}

// RangeFrom builds elementNum consecutive values from start, counting down when
// elementNum is negative.
func RangeFrom[T Integer | Float](start T, elementNum int) []T {
	step := 1
	if elementNum < 0 {
		step = -1
	}
	length := elementNum * step
	result := make([]T, length)
	for i, j := 0, start; i < length; i, j = i+1, j+T(step) {
		result[i] = j
	}
	return result
}

// SumByErr adds projections, short-circuiting on the first error.
func SumByErr[T any, R Float | Integer | Complex](collection []T, iteratee func(item T) (R, error)) (R, error) {
	var sum R
	for i := range collection {
		v, err := iteratee(collection[i])
		if err != nil {
			return sum, err
		}
		sum += v
	}
	return sum, nil
}

// ProductByErr multiplies projections, short-circuiting on the first error.
func ProductByErr[T any, R Float | Integer | Complex](collection []T, iteratee func(item T) (R, error)) (R, error) {
	var product R = 1
	for i := range collection {
		v, err := iteratee(collection[i])
		if err != nil {
			return product, err
		}
		product *= v
	}
	return product, nil
}

// MeanByErr is Mean over a fallible projection.
func MeanByErr[T any, R Float | Integer](collection []T, iteratee func(item T) (R, error)) (R, error) {
	length := R(len(collection))
	if length == 0 {
		return 0, nil
	}
	sum, err := SumByErr(collection, iteratee)
	if err != nil {
		return 0, err
	}
	return sum / length, nil
}

// RangeWithSteps builds values from start toward end by step, exclusive of end.
// Mismatched direction or a zero step yields a non-nil empty slice.
func RangeWithSteps[T Integer | Float](start, end, step T) []T {
	result := make([]T, 0)
	if start == end || step == 0 {
		return result
	}
	if start < end {
		if step < 0 {
			return result
		}
		for i := start; i < end; i += step {
			result = append(result, i)
		}
		return result
	}
	if step > 0 {
		return result
	}
	for i := start; i > end; i += step {
		result = append(result, i)
	}
	return result
}
