// Code generated by goplus from random.gp. DO NOT EDIT.
//goplus:v v0.28.0

// Package lo — randomized selection and generation.
//
// Adapted from samber/lo v1.53.0 (find.go Sample/Samples, slice.go Shuffle,
// string.go RandomString; MIT), authored in Go+. Randomness comes from the
// internal xrand shim (math/rand/v2); results are non-deterministic by design,
// so tests assert structural invariants rather than exact values.
package lo

import (
	"math"
	"strings"

	"goforge.dev/gplodash/internal/xrand"
)

const maximumCapacity = math.MaxInt>>1 + 1

// randomIntGenerator returns a pseudo-random int in [0,n).
type randomIntGenerator func(n int) int

func nearestPowerOfTwo(capacity int) int {
	n := capacity - 1
	n |= n >> 1
	n |= n >> 2
	n |= n >> 4
	n |= n >> 8
	n |= n >> 16
	if n < 0 {
		return 1
	}
	if n >= maximumCapacity {
		return maximumCapacity
	}
	return n + 1
}

// Sample returns a random element (zero value for an empty collection).
func Sample[T any](collection []T) T {
	return SampleBy(collection, xrand.IntN)
}

// SampleBy returns a random element using the supplied generator.
func SampleBy[T any](collection []T, randomIntGenerator randomIntGenerator) T {
	size := len(collection)
	if size == 0 {
		return Empty[T]()
	}
	return collection[randomIntGenerator(size)]
}

// Samples returns count random elements without replacement.
func Samples[T any, Slice ~[]T](collection Slice, count int) Slice {
	return SamplesBy(collection, count, xrand.IntN)
}

// SamplesBy returns count random elements without replacement using generator.
func SamplesBy[T any, Slice ~[]T](collection Slice, count int, randomIntGenerator randomIntGenerator) Slice {
	if count <= 0 {
		return Slice{}
	}
	size := len(collection)
	if size < count {
		count = size
	}
	indexes := Range(size)
	results := make(Slice, count)
	for i := range results {
		n := len(indexes)
		index := randomIntGenerator(n)
		results[i] = collection[indexes[index]]
		indexes[index] = indexes[n-1]
		indexes = indexes[:n-1]
	}
	return results
}

// Shuffle randomizes the order of collection in place and returns it.
func Shuffle[T any, Slice ~[]T](collection Slice) Slice {
	xrand.Shuffle(len(collection), func(i, j int) {
		collection[i], collection[j] = collection[j], collection[i]
	})
	return collection
}

// RandomString returns a random string of size runes drawn from charset. It
// panics on a non-positive size or empty charset.
func RandomString(size int, charset []rune) string {
	if size <= 0 {
		panic("lo.RandomString: size must be greater than 0")
	}
	if len(charset) == 0 {
		panic("lo.RandomString: charset must not be empty")
	}
	var sb strings.Builder
	sb.Grow(size)
	if len(charset) == 1 {
		for i := 0; i < size; i++ {
			sb.WriteRune(charset[0])
		}
		return sb.String()
	}
	letterIDBits := int(math.Log2(float64(nearestPowerOfTwo(len(charset)))))
	var letterIDMask int64 = 1<<letterIDBits - 1
	letterIDMax := 63 / letterIDBits
	for i, cache, remain := size-1, xrand.Int64(), letterIDMax; i >= 0; {
		if remain == 0 {
			cache, remain = xrand.Int64(), letterIDMax
		}
		if idx := int(cache & letterIDMask); idx < len(charset) {
			sb.WriteRune(charset[idx])
			i--
		}
		cache >>= letterIDBits
		remain--
	}
	return sb.String()
}
