// Code generated by goplus from string_case.gp. DO NOT EDIT.
//goplus:v v0.28.0

// Package lo — Unicode-aware case conversions.
//
// Adapted from samber/lo v1.53.0 string.go (MIT), authored in Go+. These use
// golang.org/x/text/cases for correct Unicode title-casing, matching upstream.
package lo

import (
	"strings"

	"golang.org/x/text/cases"
	"golang.org/x/text/language"
)

// Capitalize upper-cases the first rune (Unicode title case) and lower-cases
// the rest, per golang.org/x/text.
func Capitalize(str string) string {
	return cases.Title(language.English).String(str)
}

// PascalCase joins the words of str, each Capitalized.
func PascalCase(str string) string {
	items := Words(str)
	for i := range items {
		items[i] = Capitalize(items[i])
	}
	return strings.Join(items, "")
}

// CamelCase is PascalCase with a lower-cased first word.
func CamelCase(str string) string {
	items := Words(str)
	for i, item := range items {
		item = strings.ToLower(item)
		if i > 0 {
			item = Capitalize(item)
		}
		items[i] = item
	}
	return strings.Join(items, "")
}
